apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-deployment
  namespace: citizerve
  labels:
    app: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      namespace: citizerve
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin
        ports:
          - containerPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  namespace: citizerve
  labels:
    app: zipkin
spec:
  selector:
    app: zipkin
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
