apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: citizerve
  labels:
    app: load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  strategy: {}
  template:
    metadata:
      name: load-generator
      namespace: citizerve
      labels:
        app: load-generator
    spec:
      containers:
        - image: mcpacr2.azurecr.io/loadgenerator:v1
          name: load-generator
          resources: {}
      restartPolicy: Always
