apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-start-generator
  namespace: citizerve
  labels:
    app: no-start-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: no-start-generator
  strategy: {}
  template:
    metadata:
      name: no-start-generator
      namespace: citizerve
      labels:
        app: no-start-generator
    spec:
      containers:
        - image: bash:latest
          command:
            - "bash"
            - "-c"
            - "while true; do echo hello; sleep 10;done"
          imagePullPolicy: Always
          name: no-start-generator
          resources:
            limits:
              memory: 8Gi
            requests:
              memory: 6Gi
      restartPolicy: Always
