global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_timeout: 10s # scrape_timeout - global default is 10s.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    honor_labels: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: "citizenapi"
    metrics_path: /metrics
    scheme: http
    honor_timestamps: true
    honor_labels: true
    static_configs:
      - targets: ['citizenapi-service:3009']
  - job_name: "citizenapiotel"
    metrics_path: /metrics
    scheme: http
    honor_timestamps: true
    honor_labels: true
    static_configs:
      - targets: ['citizenapi-service:3019']
  - job_name: "resourceapi"
    metrics_path: /metrics
    scheme: http
    honor_timestamps: true
    honor_labels: true
    static_configs:
      - targets: ['resourceapi:4009']
