apiVersion: apps/v1
kind: Deployment
metadata:
  name: citizenapi
  namespace: citizerve
  labels:
    app: citizenapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citizenapi
  strategy: {}
  template:
    metadata:
      name: citizenapi
      namespace: citizerve
      labels:
        app: citizenapi
    spec:
      containers:
        - name: citizenapi
          image: mpapas/citizenapi:v4
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
            - containerPort: 3009
            - containerPort: 3019
          resources:
            limits:
              memory: 600Mi
            requests:
              memory: 300Mi
          env:
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: citizerve-secret
                  key: mongo-connection-string          
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: citizerve-configmap
                  key: NODE_ENV
            - name: OTEL_EXPORTER_ZIPKIN_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: citizerve-configmap
                  key: OTEL_EXPORTER_ZIPKIN_ENDPOINT
            - name: USE_ZIPKIN
              valueFrom:
                configMapKeyRef:
                  name: citizerve-configmap
                  key: USE_ZIPKIN
---
apiVersion: v1
kind: Service
metadata:
  name: citizenapi-service
  namespace: citizerve
  labels:
    app: citizenapi
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: citizenapi
