apiVersion: v1
kind: Secret
metadata:
  name: citizerve-secret
  namespace: citizerve
type: Opaque
data:
  mongo-connection-string: bW9uZ29kYjovL3Jvb3Q6dDMyQU5DRTkzNC0zNEBtb25nb2RiLXNlcnZpY2U6MjcwMTcvQ2l0aXplcnZlP2F1dGhTb3VyY2U9YWRtaW4=
