apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-ds-pvc
  namespace: citizerve
  labels:
    app: grafana  
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
