apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: citizerve
type: Opaque
data:
  mongo-root-username: cm9vdA==
  mongo-root-password: dDMyQU5DRTkzNC0zNA==
  mongo-url: bW9uZ29kYjovL3Jvb3Q6dDMyQU5DRTkzNC0zNEBtb25nb2RiLXNlcnZpY2U6MjcwMTcvZGI/c3NsPWZhbHNl
