apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  namespace: citizerve
  labels:
    app: mongodb    
spec:
  accessModes:
    - ReadWriteOnce 
  storageClassName: managed-csi-premium
  resources:
    requests:
      storage: 1Gi