apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  namespace: citizerve
  labels:
    app: mongodb    
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi