version: '3.8'

services:
  latency-generator:
    depends_on:
      - citizenapi-service    
    build:
      context: ../src/load-generator
      dockerfile: Dockerfile.latency.k8s
    restart: unless-stopped
