version: "3.8"

services:
  mongodb:
    image: mongo:4.4.18
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db 
  resourceapi:
    depends_on:
      - mongodb
    build: 
      context: ../src/citizerve-resourceapi
      dockerfile: Dockerfile.k8s    
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "8082:8082"
      - "4009:4009"
    environment:
      - NODE_ENV=$NODE_ENV
      #- OTEL_EXPORTER_ZIPKIN_ENDPOINT=$OTEL_EXPORTER_ZIPKIN_ENDPOINT
  citizenapi-service:
    depends_on:
      - mongodb
      - resourceapi
    build: 
      context: ../src/citizerve-citizenapi
      dockerfile: Dockerfile.k8s        
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "8081:8081"
      - "3009:3009"
      - "3019:3019"
    environment:
      - NODE_ENV=$NODE_ENV
      #- OTEL_EXPORTER_ZIPKIN_ENDPOINT=$OTEL_EXPORTER_ZIPKIN_ENDPOINT

volumes:
  db:
