version: '3.8'

services:
  jaeger-service:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      #- 5778:5778 # serve configs
      - 16686:16686 # serve Web UI
      - 14268:14268 # accept jaeger.thrift directly from clients
      - 14250:14250 # accept model.proto
      #- 9411:9411 # Zipkin compatible endpoint
      - 4317:4317 # accept OTLP
      - 4318:4318 # accept OTLP/HTTP
    restart: unless-stopped
    environment:
      #- COLLECTOR_ZIPKIN_HOST_PORT=$COLLECTOR_ZIPKIN_HOST_PORT
      - COLLECTOR_OTLP_ENABLED=$COLLECTOR_OTLP_ENABLED
