version: '3.8'

services:
  memoryleak-generator:
    depends_on:
      - citizenapi-service    
    build:
      context: ../src/load-generator
      dockerfile: Dockerfile.leakMemory.k8s
    restart: unless-stopped
