# Sourced from: https://raw.githubusercontent.com/GoogleCloudPlatform/prometheus-engine/v0.5.0/examples/frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-frontend
  namespace: citizerve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-frontend
  template:
    metadata:
      labels:
        app: prometheus-frontend
    spec:
      automountServiceAccountToken: true
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      containers:
      - name: prometheus-frontend
        image: "gke.gcr.io/prometheus-engine/frontend:v0.5.0-gke.0"
        resources:
          limits:
            memory: 600Mi
          requests:
            memory: 400Mi        
        args:
        - "--web.listen-address=:9090"
        - "--query.project-id=sandbox-michael-344216"
        ports:
        - name: web
          containerPort: 9090
        readinessProbe:
          httpGet:
            path: /-/ready
            port: web
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: web
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-frontend
  namespace: citizerve
spec:
  type: LoadBalancer
  selector:
    app: prometheus-frontend
  ports:
  - port: 9090
    targetPort: 9090
