apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: resourceapi-podmonitoring
  namespace: citizerve  
spec:
  selector:
    matchLabels:
      app: resourceapi
  endpoints:
  - port: 4009
    interval: 10s
    scheme: http
  