apiVersion: v1
kind: ConfigMap
metadata:
  name: citizerve-configmap
  namespace: citizerve
data:
  NODE_ENV: kubernetes
  OTEL_EXPORTER_ZIPKIN_ENDPOINT: http://zipkin-service:9411/api/v2/spans
  USE_ZIPKIN: 'false'
  COLLECTOR_ZIPKIN_HOST_PORT: ':9411'
  COLLECTOR_OTLP_ENABLED: 'true'
  APP_INSIGHTS_CONNECTION_STRING: 'InstrumentationKey=deed1035-3876-46aa-b7f7-e1cede397499;IngestionEndpoint=https://centralus-2.in.applicationinsights.azure.com/;LiveEndpoint=https://centralus.livediagnostics.monitor.azure.com/'
  